PAGE_SIZE: A4
DPI: 300
MARGIN_MM: 5
GAP_MM: 1
DEFAULT_BACK: resources/back.jpg
language-default: en
pages-intercalation: true
horizontal-back-offset: -2
vertical-back-offset: 0
back-oversize: 0.2
page-rotation-degrees: 0
guided-lines: true
cross-calibrator: false
